name: quiver_hub
description: "A new Flutter project for archery team attendance."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons (iOS 스타일 아이콘)
  cupertino_icons: ^1.0.8

  # Firebase 핵심 패키지
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.1

  # UI 기능 패키지
  flutter_slidable: ^3.1.2

  # 유틸리티 패키지
  image_picker: ^1.1.2
  intl: ^0.20.2
  audioplayers: ^6.5.1
  just_audio: ^0.9.40 # Grok에서 추가

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/Quiver_Hub_icon2.png"

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf