// File generated by FlutterFire CLI.
// To regenerate this file, run `flutterfire configure` from the root of your project.
// Do not modify this file manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyDvU1zZnyk39pbxkbJNWUt93kSnDva3dvM",
    appId: "1:892141263609:web:6be24bfdeb300f1d926028",
    messagingSenderId: "892141263609",
    projectId: "quiver-hub",
    authDomain: "quiver-hub.firebaseapp.com",
    storageBucket: "quiver-hub.appspot.com",
    measurementId: "G-KJQ01Y90VX",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyB37UqLA6Af0EVK0LIbQqzqyFvR6bhBD2g",
    appId: "1:892141263609:android:f435fc520acaf234926028",
    messagingSenderId: "892141263609",
    projectId: "quiver-hub",
    storageBucket: "quiver-hub.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB-_ATtdDJFJC4JUPsyd4Aa6w2yIkICzwg",
    appId: "1:892141263609:ios:304e5ff82a1e034c926028",
    messagingSenderId: "892141263609",
    projectId: "quiver-hub",
    storageBucket: "quiver-hub.appspot.com",
    iosBundleId: "com.example.quiverHub",
  );

  static const FirebaseOptions macos = ios; // macOS는 iOS 설정을 공유합니다.
}
